spring:
  application:
    name: shop-api

  datasource:
    url: jdbc:h2:mem:shop
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    mongodb:
      database: shop
      host: localhost
      port: 27017

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.2
